### PR TITLE
Adapt the dns declaration to the usage of dns zones

### LINKED ISSUE #394: Declaration DNS : adaptation to prod
in environment inferior to prod : declaration through Terraform with OVH provider.

In prod environment : manual declaration.

Be careful to use the right DNS zone on each environment (see what happened with develop deployment)

### PR DESCRIPTION
**Pull request by heroinedor**

### CODE REVIEW

**Review by ad2ien — CHANGES_REQUESTED** [review]
Nice! Adding `INGRESS_SERVICE_PORT_WEBSECURE` to `local.env.template.sh` with some explanations and we're good to go

**Comment by heroinedor** [comment]
> Nice! Adding `INGRESS_SERVICE_PORT_WEBSECURE` to `local.env.template.sh` with some explanations and we're good to go

Already done.

**Comment by heroinedor** [comment]
> Nice! Adding `INGRESS_SERVICE_PORT_WEBSECURE` to `local.env.template.sh` with some explanations and we're good to go

**Comment by heroinedor** [comment]
> Nice! Adding `INGRESS_SERVICE_PORT_WEBSECURE` to `local.env.template.sh` with some explanations and we're good to go

Already done

**Pull request merged**
